name: bff-auth

services:

- name: redis
  image: redis:6.2.5-alpine
  bindings:
    - port: 6379

- name: opa
  image: openpolicyagent/opa:0.35.0
  args: "run --server --log-format=json-pretty --log-level=debug ./tmp/api_authz_token.rego"
  volumes:
    - target: /tmp/api_authz_token.rego
      source: policy/api_authz_token.rego
    - target: /tmp/policy.rego
      source: policy/policy.rego
  bindings:
    - port: 8181
      containerPort: 8181
      protocol: http

- name: gateway
  project: backend/bff-dotnet/Gateway.csproj
  env:
    - Redis=localhost # distributed session storage
  bindings:
    - port: 8080
      protocol: https

- name: identityserver
  project: backend/identity-server/IdentityServer.csproj
  bindings:
    - port: 5001
      protocol: https

- name: sale-api
  dockerFile: backend/sale-api/Dockerfile
  env:
    - AUTH_SERVER_KEY_URL=https://host.docker.internal:5001/.well-known/openid-configuration/jwks
    - OPA_API_SERVER_URL=http://host.docker.internal:8181/v1/data/http/allow
  bindings:
    - port: 5004
      containerPort: 5004
      protocol: http
